# Generated by Django 4.2.7 on 2023-12-09 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='opinion',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='userId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='countryOfOrigin',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
