# Generated by Django 4.2.7 on 2023-12-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_userid_rating_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Rater',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='rater',
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.FloatField(default=1.0),
        ),
    ]
